import 'package:sqflite/sqflite.dart';
import '../database/salon_database.dart';
import '../models/cashier_shift.dart';
import 'cashier_shift_repository.dart';
class SqliteCashierShiftRepository implements CashierShiftRepository {
  SqliteCashierShiftRepository(this._database); final SalonDatabase _database;
  @override Future<CashierShift?> fetchOpenShift() async { final db=await _database.database; final r=await db.query('cashier_shifts',where:'closed_at IS NULL',limit:1); return r.isEmpty?null:_hydrate(db,r.first); }
  @override Future<List<CashierShift>> fetchShiftHistory({int limit=30}) async { final db=await _database.database; final rows=await db.query('cashier_shifts',orderBy:'opened_at DESC',limit:limit); final out=<CashierShift>[]; for(final r in rows){out.add(await _hydrate(db,r));} return out; }
  @override Future<List<CashMovement>> fetchMovements(String shiftId) async { final db=await _database.database; final rows=await db.query('cash_movements',where:'shift_id = ?',whereArgs:[shiftId],orderBy:'created_at ASC'); return rows.map((r)=>CashMovement(id:r['id'].toString(),shiftId:r['shift_id'].toString(),type:r['movement_type'].toString(),amount:r['amount'] as int,reason:r['reason'].toString(),createdAt:DateTime.parse(r['created_at'].toString()))).toList(); }
  @override Future<CashierShift> openShift({required int openingCash,String note=''}) async { if(openingCash<0) throw ArgumentError.value(openingCash); final db=await _database.database; final now=DateTime.now(); final id='cash-shift-${now.microsecondsSinceEpoch}'; try { await db.insert('cashier_shifts',{'id':id,'opening_cash':openingCash,'opened_at':now.toIso8601String(),'note':note.trim()},conflictAlgorithm:ConflictAlgorithm.abort); } on DatabaseException { throw StateError('Đang có một ca thu ngân chưa chốt.'); } return (await fetchOpenShift())!; }
  @override Future<CashMovement> recordCashMovement({required String type,required int amount,required String reason}) async { if(type!='in'&&type!='out') throw ArgumentError.value(type); if(amount<=0) throw ArgumentError.value(amount); if(reason.trim().isEmpty) throw ArgumentError('Lý do thu/chi không được để trống.'); final db=await _database.database; final shift=await fetchOpenShift(); if(shift==null) throw StateError('Chưa mở ca thu ngân.'); final now=DateTime.now(); final m=CashMovement(id:'cash-move-${now.microsecondsSinceEpoch}',shiftId:shift.id,type:type,amount:amount,reason:reason.trim(),createdAt:now); await db.insert('cash_movements',{'id':m.id,'shift_id':m.shiftId,'movement_type':m.type,'amount':m.amount,'reason':m.reason,'created_at':now.toIso8601String()}); return m; }
  @override Future<CashierShift> closeShift({required int countedCash,String note=''}) async { if(countedCash<0) throw ArgumentError.value(countedCash); final db=await _database.database; return db.transaction((tx) async { final rows=await tx.query('cashier_shifts',where:'closed_at IS NULL',limit:1); if(rows.isEmpty) throw StateError('Không có ca thu ngân đang mở.'); final s=await _hydrate(tx,rows.first); final now=DateTime.now(), expected=s.liveExpectedCash, variance=countedCash-expected; await tx.update('cashier_shifts',{'closed_at':now.toIso8601String(),'counted_cash':countedCash,'expected_cash':expected,'variance':variance,'note':note.trim().isEmpty?s.note:note.trim()},where:'id = ?',whereArgs:[s.id]); final closed=(await tx.query('cashier_shifts',where:'id = ?',whereArgs:[s.id],limit:1)).first; return _hydrate(tx,closed); }); }
  Future<CashierShift> _hydrate(DatabaseExecutor db,Map<String,Object?> row) async { final opened=DateTime.parse(row['opened_at'].toString()); final closed=row['closed_at']==null?null:DateTime.parse(row['closed_at'].toString()); final sales=await db.rawQuery("SELECT COALESCE(SUM(CASE WHEN EXISTS (SELECT 1 FROM invoice_payments p0 WHERE p0.invoice_id=i.id) THEN COALESCE((SELECT SUM(p.amount) FROM invoice_payments p WHERE p.invoice_id=i.id AND p.payment_method='Tiền mặt'),0) WHEN i.payment_method='Tiền mặt' THEN i.total_amount ELSE 0 END),0) total FROM invoices i WHERE i.paid_at IS NOT NULL AND i.paid_at>=? AND i.paid_at<=? AND NOT EXISTS (SELECT 1 FROM invoice_adjustments a WHERE a.invoice_id=i.id)",[opened.toIso8601String(),(closed??DateTime.now()).toIso8601String()]); final moves=await db.rawQuery("SELECT COALESCE(SUM(CASE WHEN movement_type='in' THEN amount ELSE 0 END),0) cash_in, COALESCE(SUM(CASE WHEN movement_type='out' THEN amount ELSE 0 END),0) cash_out FROM cash_movements WHERE shift_id=?",[row['id']]); int n(Object? v)=>v is int?v:int.tryParse(v?.toString()??'')??0; return CashierShift(id:row['id'].toString(),openingCash:n(row['opening_cash']),openedAt:opened,closedAt:closed,countedCash:row['counted_cash']==null?null:n(row['counted_cash']),expectedCash:row['expected_cash']==null?null:n(row['expected_cash']),variance:row['variance']==null?null:n(row['variance']),note:row['note']?.toString()??'',cashSales:n(sales.first['total']),cashIn:n(moves.first['cash_in']),cashOut:n(moves.first['cash_out'])); }
}
